print("-----------------------------------------")
print("Tugas 1 Sistem Operasi Kelas B")
print("-----------------------------------------")
print("Nama : Alisa Jihan Azizah")
print("NPM  : 21083010064")
print("-----------------------------------------")
print("Notes : ")
print("-----------------------------------------")
print("Hello World")
print("Ini adalah skrip bash pertamaku di linux")
